### ISSUE TITLE
polylang-revslider - Critical Error

### ISSUE THREAD

**Issue by attila729** [stuffo/polylang-revslider#2]
Hi I had the php7.4 version and installed the snippets plugin and entered the php code you indicated and everything worked fine. I migrated the site to another hosting where there is php 8.0, the site works correctly even with translated riverslider, but when I go to the wordpress back office and go to the river sladier settings I get written critical error and does not allow me to access river slider. How can I fix it all? I tried to deactivate your code and riverslider works correctly but it doesn't allow me to do the multilingual tradition. Help me solve the problem thanks

**Comment by stuffo** [comment]
sorry, i don't maintain this plugin anymore.
