### ISSUE TITLE
WP critical error

### ISSUE THREAD

**Issue by swinili** [stuffo/polylang-revslider#3]
Hey there, the snippet worked great for 3 years, but now I got a critical error in rev slider.
>> revolution slider menu couldn't be opened any more.
Deactivating the code in functions.php of child theme worked for reactivating RS Plugin.
Do you have any update for your code? It would be great, to get the translated sliders work again...
Thanks so far and greets
Sabine

**Comment by stuffo** [comment]
sorry to hear this. i don't maintain this code anymore. google for your error, maybe you find a hint.
